services:
  db:
    image: postgres:latest
    container_name: bookclub_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bookclub
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
